# Generated by Django 4.2.13 on 2024-07-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_owner',
            field=models.BooleanField(default=False, verbose_name='Is owner'),
        ),
    ]
