# Generated by Django 4.2.13 on 2024-07-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='image',
            field=models.ImageField(upload_to='appointment_images/'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='image',
            field=models.ImageField(upload_to='salon_images/'),
        ),
    ]
