# Generated by Django 4.2.13 on 2024-07-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_alter_appointment_image_alter_salon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
